// Code generated by ent, DO NOT EDIT.

package usagestat

import (
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldID, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldDate, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldAPIKeyID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldProjectID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldChannelID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldModelID, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldRequestCount, v))
}

// PromptTokens applies equality check predicate on the "prompt_tokens" field. It's identical to PromptTokensEQ.
func PromptTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldPromptTokens, v))
}

// CompletionTokens applies equality check predicate on the "completion_tokens" field. It's identical to CompletionTokensEQ.
func CompletionTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCompletionTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTotalTokens, v))
}

// PromptCachedTokens applies equality check predicate on the "prompt_cached_tokens" field. It's identical to PromptCachedTokensEQ.
func PromptCachedTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldPromptCachedTokens, v))
}

// PromptWriteCachedTokens applies equality check predicate on the "prompt_write_cached_tokens" field. It's identical to PromptWriteCachedTokensEQ.
func PromptWriteCachedTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldPromptWriteCachedTokens, v))
}

// CompletionReasoningTokens applies equality check predicate on the "completion_reasoning_tokens" field. It's identical to CompletionReasoningTokensEQ.
func CompletionReasoningTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCompletionReasoningTokens, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTotalCost, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldDate, v))
}

// DateContains applies the Contains predicate on the "date" field.
func DateContains(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldContains(FieldDate, v))
}

// DateHasPrefix applies the HasPrefix predicate on the "date" field.
func DateHasPrefix(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldHasPrefix(FieldDate, v))
}

// DateHasSuffix applies the HasSuffix predicate on the "date" field.
func DateHasSuffix(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldHasSuffix(FieldDate, v))
}

// DateEqualFold applies the EqualFold predicate on the "date" field.
func DateEqualFold(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEqualFold(FieldDate, v))
}

// DateContainsFold applies the ContainsFold predicate on the "date" field.
func DateContainsFold(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldContainsFold(FieldDate, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldAPIKeyID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldProjectID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldChannelID, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldContainsFold(FieldModelID, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldRequestCount, v))
}

// PromptTokensEQ applies the EQ predicate on the "prompt_tokens" field.
func PromptTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldPromptTokens, v))
}

// PromptTokensNEQ applies the NEQ predicate on the "prompt_tokens" field.
func PromptTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldPromptTokens, v))
}

// PromptTokensIn applies the In predicate on the "prompt_tokens" field.
func PromptTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldPromptTokens, vs...))
}

// PromptTokensNotIn applies the NotIn predicate on the "prompt_tokens" field.
func PromptTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldPromptTokens, vs...))
}

// PromptTokensGT applies the GT predicate on the "prompt_tokens" field.
func PromptTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldPromptTokens, v))
}

// PromptTokensGTE applies the GTE predicate on the "prompt_tokens" field.
func PromptTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldPromptTokens, v))
}

// PromptTokensLT applies the LT predicate on the "prompt_tokens" field.
func PromptTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldPromptTokens, v))
}

// PromptTokensLTE applies the LTE predicate on the "prompt_tokens" field.
func PromptTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldPromptTokens, v))
}

// CompletionTokensEQ applies the EQ predicate on the "completion_tokens" field.
func CompletionTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCompletionTokens, v))
}

// CompletionTokensNEQ applies the NEQ predicate on the "completion_tokens" field.
func CompletionTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldCompletionTokens, v))
}

// CompletionTokensIn applies the In predicate on the "completion_tokens" field.
func CompletionTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldCompletionTokens, vs...))
}

// CompletionTokensNotIn applies the NotIn predicate on the "completion_tokens" field.
func CompletionTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldCompletionTokens, vs...))
}

// CompletionTokensGT applies the GT predicate on the "completion_tokens" field.
func CompletionTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldCompletionTokens, v))
}

// CompletionTokensGTE applies the GTE predicate on the "completion_tokens" field.
func CompletionTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldCompletionTokens, v))
}

// CompletionTokensLT applies the LT predicate on the "completion_tokens" field.
func CompletionTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldCompletionTokens, v))
}

// CompletionTokensLTE applies the LTE predicate on the "completion_tokens" field.
func CompletionTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldCompletionTokens, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldTotalTokens, v))
}

// PromptCachedTokensEQ applies the EQ predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldPromptCachedTokens, v))
}

// PromptCachedTokensNEQ applies the NEQ predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldPromptCachedTokens, v))
}

// PromptCachedTokensIn applies the In predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldPromptCachedTokens, vs...))
}

// PromptCachedTokensNotIn applies the NotIn predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldPromptCachedTokens, vs...))
}

// PromptCachedTokensGT applies the GT predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldPromptCachedTokens, v))
}

// PromptCachedTokensGTE applies the GTE predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldPromptCachedTokens, v))
}

// PromptCachedTokensLT applies the LT predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldPromptCachedTokens, v))
}

// PromptCachedTokensLTE applies the LTE predicate on the "prompt_cached_tokens" field.
func PromptCachedTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldPromptCachedTokens, v))
}

// PromptWriteCachedTokensEQ applies the EQ predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldPromptWriteCachedTokens, v))
}

// PromptWriteCachedTokensNEQ applies the NEQ predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldPromptWriteCachedTokens, v))
}

// PromptWriteCachedTokensIn applies the In predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldPromptWriteCachedTokens, vs...))
}

// PromptWriteCachedTokensNotIn applies the NotIn predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldPromptWriteCachedTokens, vs...))
}

// PromptWriteCachedTokensGT applies the GT predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldPromptWriteCachedTokens, v))
}

// PromptWriteCachedTokensGTE applies the GTE predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldPromptWriteCachedTokens, v))
}

// PromptWriteCachedTokensLT applies the LT predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldPromptWriteCachedTokens, v))
}

// PromptWriteCachedTokensLTE applies the LTE predicate on the "prompt_write_cached_tokens" field.
func PromptWriteCachedTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldPromptWriteCachedTokens, v))
}

// CompletionReasoningTokensEQ applies the EQ predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCompletionReasoningTokens, v))
}

// CompletionReasoningTokensNEQ applies the NEQ predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldCompletionReasoningTokens, v))
}

// CompletionReasoningTokensIn applies the In predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldCompletionReasoningTokens, vs...))
}

// CompletionReasoningTokensNotIn applies the NotIn predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldCompletionReasoningTokens, vs...))
}

// CompletionReasoningTokensGT applies the GT predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldCompletionReasoningTokens, v))
}

// CompletionReasoningTokensGTE applies the GTE predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldCompletionReasoningTokens, v))
}

// CompletionReasoningTokensLT applies the LT predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldCompletionReasoningTokens, v))
}

// CompletionReasoningTokensLTE applies the LTE predicate on the "completion_reasoning_tokens" field.
func CompletionReasoningTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldCompletionReasoningTokens, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldTotalCost, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageStat) predicate.UsageStat {
	return predicate.UsageStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageStat) predicate.UsageStat {
	return predicate.UsageStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageStat) predicate.UsageStat {
	return predicate.UsageStat(sql.NotPredicates(p))
}
