version: 2

project_name: axonhub

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    main: ./cmd/axonhub
    binary: axonhub
    hooks:
      pre:
        - make build-frontend
    ldflags:
      - -s -w -X github.com/looplj/axonhub/internal/build.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le

release:
  draft: true

archives:
  - id: archive
    ids: [build]
    formats: [zip]
    files:
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'