version: 2

project_name: axonhub

dist: .builds

before:
  hooks:
    - /bin/sh -c 'cd deploy && chmod +x *.sh'
    - make build-frontend
    - go mod tidy

builds:
  - id: build
    main: ./cmd/axonhub
    binary: axonhub
    ldflags:
      - -s -w -X github.com/looplj/axonhub/internal/build.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - loong64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: loong64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: loong64

release:
  draft: true

archives:
  - id: archive
    ids: [build]
    formats: [zip]
    files:
      - LICENSE
      - CHANGELOG.md
      - src: deploy/install.sh
        dst: install.sh
      - src: deploy/start.sh
        dst: start.sh
      - src: deploy/stop.sh
        dst: stop.sh
      - src: deploy/install.ps1
        dst: install.ps1
      - src: deploy/start.ps1
        dst: start.ps1
      - src: deploy/stop.ps1
        dst: stop.ps1
      - src: deploy/install.bat
        dst: install.bat
      - src: deploy/start.bat
        dst: start.bat
      - src: deploy/stop.bat
        dst: stop.bat

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'