repos:
  - repo: 'https://github.com/golangci/golangci-lint'
    rev: v2.3.1
    hooks:
      - id: golangci-lint
        entry: golangci-lint run -vvv

  - repo: local
    hooks:
      - id: run-go-test
        name: Run go test
        entry: bash -c 'go test ./... --short'
        language: system
        types: [go]
        pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      #      - id: go-build
      - id: go-mod-tidy

