// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "enabled"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "user_id", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_projects_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[9]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_keys_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10]},
			},
			{
				Name:    "api_keys_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[9]},
			},
			{
				Name:    "api_keys_by_key",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai", "vercel", "anthropic", "anthropic_aws", "anthropic_gcp", "gemini_openai", "deepseek", "deepseek_anthropic", "doubao", "moonshot", "moonshot_anthropic", "zhipu", "zai", "zhipu_anthropic", "zai_anthropic", "anthropic_fake", "openai_fake", "openrouter", "xai", "ppio", "siliconflow", "volcengine", "longcat", "longcat_anthropic", "minimax", "minimax_anthropic", "aihubmix", "burncloud"}},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "credentials", Type: field.TypeJSON},
		{Name: "supported_models", Type: field.TypeJSON},
		{Name: "default_test_model", Type: field.TypeString},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "ordering_weight", Type: field.TypeInt, Default: 0},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channels_by_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelsColumns[6], ChannelsColumns[3]},
			},
		},
	}
	// DataStoragesColumns holds the columns for the "data_storages" table.
	DataStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "primary", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"database", "fs", "s3", "gcs"}},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
	}
	// DataStoragesTable holds the schema information for the "data_storages" table.
	DataStoragesTable = &schema.Table{
		Name:       "data_storages",
		Columns:    DataStoragesColumns,
		PrimaryKey: []*schema.Column{DataStoragesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "data_sources_by_name",
				Unique:  true,
				Columns: []*schema.Column{DataStoragesColumns[4]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "projects_by_name",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[4]},
			},
		},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "trace_id", Type: field.TypeInt, Nullable: true},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_api_keys_requests",
				Columns:    []*schema.Column{RequestsColumns[12]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_channels_requests",
				Columns:    []*schema.Column{RequestsColumns[13]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_data_storages_requests",
				Columns:    []*schema.Column{RequestsColumns[14]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_projects_requests",
				Columns:    []*schema.Column{RequestsColumns[15]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "requests_traces_requests",
				Columns:    []*schema.Column{RequestsColumns[16]},
				RefColumns: []*schema.Column{TracesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requests_by_api_key_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[12]},
			},
			{
				Name:    "requests_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[15]},
			},
			{
				Name:    "requests_by_channel_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[13]},
			},
			{
				Name:    "requests_by_trace_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[16]},
			},
			{
				Name:    "requests_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[1]},
			},
			{
				Name:    "requests_by_status",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[10]},
			},
		},
	}
	// RequestExecutionsColumns holds the columns for the "request_executions" table.
	RequestExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeInt},
	}
	// RequestExecutionsTable holds the schema information for the "request_executions" table.
	RequestExecutionsTable = &schema.Table{
		Name:       "request_executions",
		Columns:    RequestExecutionsColumns,
		PrimaryKey: []*schema.Column{RequestExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_executions_channels_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[12]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_data_storages_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[13]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_requests_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[14]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_executions_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[14]},
			},
			{
				Name:    "request_executions_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[12]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"system", "project"}, Default: "system"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_projects_roles",
				Columns:    []*schema.Column{RolesColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "roles_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[7], RolesColumns[4]},
			},
			{
				Name:    "roles_by_level",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[5]},
			},
		},
	}
	// SystemsColumns holds the columns for the "systems" table.
	SystemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"mysql": "mediumtext"}},
	}
	// SystemsTable holds the schema information for the "systems" table.
	SystemsTable = &schema.Table{
		Name:       "systems",
		Columns:    SystemsColumns,
		PrimaryKey: []*schema.Column{SystemsColumns[0]},
	}
	// ThreadsColumns holds the columns for the "threads" table.
	ThreadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "thread_id", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
	}
	// ThreadsTable holds the schema information for the "threads" table.
	ThreadsTable = &schema.Table{
		Name:       "threads",
		Columns:    ThreadsColumns,
		PrimaryKey: []*schema.Column{ThreadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "threads_projects_threads",
				Columns:    []*schema.Column{ThreadsColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "threads_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{ThreadsColumns[4]},
			},
			{
				Name:    "threads_by_thread_id",
				Unique:  true,
				Columns: []*schema.Column{ThreadsColumns[3]},
			},
		},
	}
	// TracesColumns holds the columns for the "traces" table.
	TracesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "trace_id", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "thread_id", Type: field.TypeInt, Nullable: true},
	}
	// TracesTable holds the schema information for the "traces" table.
	TracesTable = &schema.Table{
		Name:       "traces",
		Columns:    TracesColumns,
		PrimaryKey: []*schema.Column{TracesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "traces_projects_traces",
				Columns:    []*schema.Column{TracesColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "traces_threads_traces",
				Columns:    []*schema.Column{TracesColumns[5]},
				RefColumns: []*schema.Column{ThreadsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "traces_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[4]},
			},
			{
				Name:    "traces_by_trace_id",
				Unique:  true,
				Columns: []*schema.Column{TracesColumns[3]},
			},
			{
				Name:    "traces_by_thread_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[5]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "model_id", Type: field.TypeString},
		{Name: "prompt_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "completion_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "prompt_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_reasoning_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_accepted_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_rejected_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "request_id", Type: field.TypeInt},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_channels_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[15]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_projects_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[16]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_requests_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[17]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usage_logs_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[17]},
			},
			{
				Name:    "usage_logs_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[16]},
			},
			{
				Name:    "usage_logs_by_channel_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[15]},
			},
			{
				Name:    "usage_logs_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_model_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[3]},
			},
			{
				Name:    "usage_logs_by_project_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[16], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_channel_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[15], UsageLogsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"activated", "deactivated"}, Default: "activated"},
		{Name: "prefer_language", Type: field.TypeString, Default: "en"},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "mediumtext"}},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserProjectsColumns holds the columns for the "user_projects" table.
	UserProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "project_id", Type: field.TypeInt},
	}
	// UserProjectsTable holds the schema information for the "user_projects" table.
	UserProjectsTable = &schema.Table{
		Name:       "user_projects",
		Columns:    UserProjectsColumns,
		PrimaryKey: []*schema.Column{UserProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_projects_users_user",
				Columns:    []*schema.Column{UserProjectsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_projects_projects_project",
				Columns:    []*schema.Column{UserProjectsColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_projects_by_user_id_project_id",
				Unique:  true,
				Columns: []*schema.Column{UserProjectsColumns[6], UserProjectsColumns[7], UserProjectsColumns[3]},
			},
			{
				Name:    "user_projects_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{UserProjectsColumns[7]},
			},
			{
				Name:    "userproject_project_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{UserProjectsColumns[7], UserProjectsColumns[6]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_users_user",
				Columns:    []*schema.Column{UserRolesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_roles_role",
				Columns:    []*schema.Column{UserRolesColumns[5]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_roles_by_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[4], UserRolesColumns[5], UserRolesColumns[1]},
			},
			{
				Name:    "user_roles_by_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[5]},
			},
			{
				Name:    "userrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[4], UserRolesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		ChannelsTable,
		DataStoragesTable,
		ProjectsTable,
		RequestsTable,
		RequestExecutionsTable,
		RolesTable,
		SystemsTable,
		ThreadsTable,
		TracesTable,
		UsageLogsTable,
		UsersTable,
		UserProjectsTable,
		UserRolesTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = ProjectsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	RequestsTable.ForeignKeys[0].RefTable = APIKeysTable
	RequestsTable.ForeignKeys[1].RefTable = ChannelsTable
	RequestsTable.ForeignKeys[2].RefTable = DataStoragesTable
	RequestsTable.ForeignKeys[3].RefTable = ProjectsTable
	RequestsTable.ForeignKeys[4].RefTable = TracesTable
	RequestExecutionsTable.ForeignKeys[0].RefTable = ChannelsTable
	RequestExecutionsTable.ForeignKeys[1].RefTable = DataStoragesTable
	RequestExecutionsTable.ForeignKeys[2].RefTable = RequestsTable
	RolesTable.ForeignKeys[0].RefTable = ProjectsTable
	ThreadsTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[1].RefTable = ThreadsTable
	UsageLogsTable.ForeignKeys[0].RefTable = ChannelsTable
	UsageLogsTable.ForeignKeys[1].RefTable = ProjectsTable
	UsageLogsTable.ForeignKeys[2].RefTable = RequestsTable
	UserProjectsTable.ForeignKeys[0].RefTable = UsersTable
	UserProjectsTable.ForeignKeys[1].RefTable = ProjectsTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
}
