// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentinstance"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// AgentInstanceUpdate is the builder for updating AgentInstance entities.
type AgentInstanceUpdate struct {
	config
	hooks     []Hook
	mutation  *AgentInstanceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AgentInstanceUpdate builder.
func (_u *AgentInstanceUpdate) Where(ps ...predicate.AgentInstance) *AgentInstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentInstanceUpdate) SetUpdatedAt(v time.Time) *AgentInstanceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentInstanceUpdate) SetDeletedAt(v int) *AgentInstanceUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentInstanceUpdate) SetNillableDeletedAt(v *int) *AgentInstanceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AgentInstanceUpdate) AddDeletedAt(v int) *AgentInstanceUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentInstanceUpdate) SetName(v string) *AgentInstanceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentInstanceUpdate) SetNillableName(v *string) *AgentInstanceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AgentInstanceUpdate) SetPlatform(v string) *AgentInstanceUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AgentInstanceUpdate) SetNillablePlatform(v *string) *AgentInstanceUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentInstanceUpdate) SetVersion(v string) *AgentInstanceUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentInstanceUpdate) SetNillableVersion(v *string) *AgentInstanceUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *AgentInstanceUpdate) SetLastHeartbeatAt(v time.Time) *AgentInstanceUpdate {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *AgentInstanceUpdate) SetNillableLastHeartbeatAt(v *time.Time) *AgentInstanceUpdate {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// Mutation returns the AgentInstanceMutation object of the builder.
func (_u *AgentInstanceUpdate) Mutation() *AgentInstanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentInstanceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentInstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentInstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentInstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentInstanceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentinstance.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentinstance.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentinstance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentInstanceUpdate) check() error {
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentInstance.agent"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentInstanceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentInstanceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentInstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentinstance.Table, agentinstance.Columns, sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentinstance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentinstance.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(agentinstance.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentinstance.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(agentinstance.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agentinstance.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(agentinstance.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentInstanceUpdateOne is the builder for updating a single AgentInstance entity.
type AgentInstanceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AgentInstanceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentInstanceUpdateOne) SetUpdatedAt(v time.Time) *AgentInstanceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentInstanceUpdateOne) SetDeletedAt(v int) *AgentInstanceUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentInstanceUpdateOne) SetNillableDeletedAt(v *int) *AgentInstanceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AgentInstanceUpdateOne) AddDeletedAt(v int) *AgentInstanceUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentInstanceUpdateOne) SetName(v string) *AgentInstanceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentInstanceUpdateOne) SetNillableName(v *string) *AgentInstanceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AgentInstanceUpdateOne) SetPlatform(v string) *AgentInstanceUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AgentInstanceUpdateOne) SetNillablePlatform(v *string) *AgentInstanceUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentInstanceUpdateOne) SetVersion(v string) *AgentInstanceUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentInstanceUpdateOne) SetNillableVersion(v *string) *AgentInstanceUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *AgentInstanceUpdateOne) SetLastHeartbeatAt(v time.Time) *AgentInstanceUpdateOne {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *AgentInstanceUpdateOne) SetNillableLastHeartbeatAt(v *time.Time) *AgentInstanceUpdateOne {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// Mutation returns the AgentInstanceMutation object of the builder.
func (_u *AgentInstanceUpdateOne) Mutation() *AgentInstanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentInstanceUpdate builder.
func (_u *AgentInstanceUpdateOne) Where(ps ...predicate.AgentInstance) *AgentInstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentInstanceUpdateOne) Select(field string, fields ...string) *AgentInstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentInstance entity.
func (_u *AgentInstanceUpdateOne) Save(ctx context.Context) (*AgentInstance, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentInstanceUpdateOne) SaveX(ctx context.Context) *AgentInstance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentInstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentInstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentInstanceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentinstance.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentinstance.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentinstance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentInstanceUpdateOne) check() error {
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentInstance.agent"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentInstanceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentInstanceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentInstanceUpdateOne) sqlSave(ctx context.Context) (_node *AgentInstance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentinstance.Table, agentinstance.Columns, sqlgraph.NewFieldSpec(agentinstance.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentInstance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentinstance.FieldID)
		for _, f := range fields {
			if !agentinstance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentinstance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentinstance.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(agentinstance.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentinstance.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(agentinstance.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agentinstance.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(agentinstance.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AgentInstance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
