// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (ak *APIKey) User(ctx context.Context) (*User, error) {
	result, err := ak.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = ak.QueryUser().Only(ctx)
	}
	return result, err
}

func (ak *APIKey) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := ak.Edges.totalCount[1][alias]
	if nodes, err := ak.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return ak.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (c *Channel) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := c.Edges.totalCount[0][alias]
	if nodes, err := c.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return c.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (c *Channel) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := c.Edges.totalCount[1][alias]
	if nodes, err := c.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return c.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (r *Request) User(ctx context.Context) (*User, error) {
	result, err := r.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryUser().Only(ctx)
	}
	return result, err
}

func (r *Request) APIKey(ctx context.Context) (*APIKey, error) {
	result, err := r.Edges.APIKeyOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryAPIKey().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (r *Request) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := r.Edges.totalCount[2][alias]
	if nodes, err := r.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return r.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (r *Request) Channel(ctx context.Context) (*Channel, error) {
	result, err := r.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (re *RequestExecution) Request(ctx context.Context) (*Request, error) {
	result, err := re.Edges.RequestOrErr()
	if IsNotLoaded(err) {
		result, err = re.QueryRequest().Only(ctx)
	}
	return result, err
}

func (re *RequestExecution) Channel(ctx context.Context) (*Channel, error) {
	result, err := re.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = re.QueryChannel().Only(ctx)
	}
	return result, err
}

func (r *Role) Users(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserOrder, where *UserWhereInput,
) (*UserConnection, error) {
	opts := []UserPaginateOption{
		WithUserOrder(orderBy),
		WithUserFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := r.Edges.totalCount[0][alias]
	if nodes, err := r.NamedUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserConnection{Edges: []*UserEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return r.QueryUsers().Paginate(ctx, after, first, before, last, opts...)
}

func (u *User) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[0][alias]
	if nodes, err := u.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return u.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (u *User) APIKeys(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *APIKeyOrder, where *APIKeyWhereInput,
) (*APIKeyConnection, error) {
	opts := []APIKeyPaginateOption{
		WithAPIKeyOrder(orderBy),
		WithAPIKeyFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[1][alias]
	if nodes, err := u.NamedAPIKeys(alias); err == nil || hasTotalCount {
		pager, err := newAPIKeyPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &APIKeyConnection{Edges: []*APIKeyEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return u.QueryAPIKeys().Paginate(ctx, after, first, before, last, opts...)
}

func (u *User) Roles(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RoleOrder, where *RoleWhereInput,
) (*RoleConnection, error) {
	opts := []RolePaginateOption{
		WithRoleOrder(orderBy),
		WithRoleFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[2][alias]
	if nodes, err := u.NamedRoles(alias); err == nil || hasTotalCount {
		pager, err := newRolePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RoleConnection{Edges: []*RoleEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return u.QueryRoles().Paginate(ctx, after, first, before, last, opts...)
}
