// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/usagestat"
)

// UsageStatUpdate is the builder for updating UsageStat entities.
type UsageStatUpdate struct {
	config
	hooks     []Hook
	mutation  *UsageStatMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UsageStatUpdate builder.
func (_u *UsageStatUpdate) Where(ps ...predicate.UsageStat) *UsageStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageStatUpdate) SetRequestCount(v int64) *UsageStatUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillableRequestCount(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageStatUpdate) AddRequestCount(v int64) *UsageStatUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_u *UsageStatUpdate) SetPromptTokens(v int64) *UsageStatUpdate {
	_u.mutation.ResetPromptTokens()
	_u.mutation.SetPromptTokens(v)
	return _u
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillablePromptTokens(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetPromptTokens(*v)
	}
	return _u
}

// AddPromptTokens adds value to the "prompt_tokens" field.
func (_u *UsageStatUpdate) AddPromptTokens(v int64) *UsageStatUpdate {
	_u.mutation.AddPromptTokens(v)
	return _u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_u *UsageStatUpdate) SetCompletionTokens(v int64) *UsageStatUpdate {
	_u.mutation.ResetCompletionTokens()
	_u.mutation.SetCompletionTokens(v)
	return _u
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillableCompletionTokens(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetCompletionTokens(*v)
	}
	return _u
}

// AddCompletionTokens adds value to the "completion_tokens" field.
func (_u *UsageStatUpdate) AddCompletionTokens(v int64) *UsageStatUpdate {
	_u.mutation.AddCompletionTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *UsageStatUpdate) SetTotalTokens(v int64) *UsageStatUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillableTotalTokens(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *UsageStatUpdate) AddTotalTokens(v int64) *UsageStatUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetPromptCachedTokens sets the "prompt_cached_tokens" field.
func (_u *UsageStatUpdate) SetPromptCachedTokens(v int64) *UsageStatUpdate {
	_u.mutation.ResetPromptCachedTokens()
	_u.mutation.SetPromptCachedTokens(v)
	return _u
}

// SetNillablePromptCachedTokens sets the "prompt_cached_tokens" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillablePromptCachedTokens(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetPromptCachedTokens(*v)
	}
	return _u
}

// AddPromptCachedTokens adds value to the "prompt_cached_tokens" field.
func (_u *UsageStatUpdate) AddPromptCachedTokens(v int64) *UsageStatUpdate {
	_u.mutation.AddPromptCachedTokens(v)
	return _u
}

// SetPromptWriteCachedTokens sets the "prompt_write_cached_tokens" field.
func (_u *UsageStatUpdate) SetPromptWriteCachedTokens(v int64) *UsageStatUpdate {
	_u.mutation.ResetPromptWriteCachedTokens()
	_u.mutation.SetPromptWriteCachedTokens(v)
	return _u
}

// SetNillablePromptWriteCachedTokens sets the "prompt_write_cached_tokens" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillablePromptWriteCachedTokens(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetPromptWriteCachedTokens(*v)
	}
	return _u
}

// AddPromptWriteCachedTokens adds value to the "prompt_write_cached_tokens" field.
func (_u *UsageStatUpdate) AddPromptWriteCachedTokens(v int64) *UsageStatUpdate {
	_u.mutation.AddPromptWriteCachedTokens(v)
	return _u
}

// SetCompletionReasoningTokens sets the "completion_reasoning_tokens" field.
func (_u *UsageStatUpdate) SetCompletionReasoningTokens(v int64) *UsageStatUpdate {
	_u.mutation.ResetCompletionReasoningTokens()
	_u.mutation.SetCompletionReasoningTokens(v)
	return _u
}

// SetNillableCompletionReasoningTokens sets the "completion_reasoning_tokens" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillableCompletionReasoningTokens(v *int64) *UsageStatUpdate {
	if v != nil {
		_u.SetCompletionReasoningTokens(*v)
	}
	return _u
}

// AddCompletionReasoningTokens adds value to the "completion_reasoning_tokens" field.
func (_u *UsageStatUpdate) AddCompletionReasoningTokens(v int64) *UsageStatUpdate {
	_u.mutation.AddCompletionReasoningTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *UsageStatUpdate) SetTotalCost(v float64) *UsageStatUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *UsageStatUpdate) SetNillableTotalCost(v *float64) *UsageStatUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *UsageStatUpdate) AddTotalCost(v float64) *UsageStatUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// Mutation returns the UsageStatMutation object of the builder.
func (_u *UsageStatUpdate) Mutation() *UsageStatMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageStatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UsageStatUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsageStatUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UsageStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usagestat.Table, usagestat.Columns, sqlgraph.NewFieldSpec(usagestat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usagestat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usagestat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PromptTokens(); ok {
		_spec.SetField(usagestat.FieldPromptTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPromptTokens(); ok {
		_spec.AddField(usagestat.FieldPromptTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompletionTokens(); ok {
		_spec.SetField(usagestat.FieldCompletionTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletionTokens(); ok {
		_spec.AddField(usagestat.FieldCompletionTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(usagestat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(usagestat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PromptCachedTokens(); ok {
		_spec.SetField(usagestat.FieldPromptCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPromptCachedTokens(); ok {
		_spec.AddField(usagestat.FieldPromptCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PromptWriteCachedTokens(); ok {
		_spec.SetField(usagestat.FieldPromptWriteCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPromptWriteCachedTokens(); ok {
		_spec.AddField(usagestat.FieldPromptWriteCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompletionReasoningTokens(); ok {
		_spec.SetField(usagestat.FieldCompletionReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletionReasoningTokens(); ok {
		_spec.AddField(usagestat.FieldCompletionReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(usagestat.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(usagestat.FieldTotalCost, field.TypeFloat64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagestat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageStatUpdateOne is the builder for updating a single UsageStat entity.
type UsageStatUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UsageStatMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageStatUpdateOne) SetRequestCount(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillableRequestCount(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageStatUpdateOne) AddRequestCount(v int64) *UsageStatUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_u *UsageStatUpdateOne) SetPromptTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetPromptTokens()
	_u.mutation.SetPromptTokens(v)
	return _u
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillablePromptTokens(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetPromptTokens(*v)
	}
	return _u
}

// AddPromptTokens adds value to the "prompt_tokens" field.
func (_u *UsageStatUpdateOne) AddPromptTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.AddPromptTokens(v)
	return _u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_u *UsageStatUpdateOne) SetCompletionTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetCompletionTokens()
	_u.mutation.SetCompletionTokens(v)
	return _u
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillableCompletionTokens(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetCompletionTokens(*v)
	}
	return _u
}

// AddCompletionTokens adds value to the "completion_tokens" field.
func (_u *UsageStatUpdateOne) AddCompletionTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.AddCompletionTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *UsageStatUpdateOne) SetTotalTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillableTotalTokens(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *UsageStatUpdateOne) AddTotalTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetPromptCachedTokens sets the "prompt_cached_tokens" field.
func (_u *UsageStatUpdateOne) SetPromptCachedTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetPromptCachedTokens()
	_u.mutation.SetPromptCachedTokens(v)
	return _u
}

// SetNillablePromptCachedTokens sets the "prompt_cached_tokens" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillablePromptCachedTokens(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetPromptCachedTokens(*v)
	}
	return _u
}

// AddPromptCachedTokens adds value to the "prompt_cached_tokens" field.
func (_u *UsageStatUpdateOne) AddPromptCachedTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.AddPromptCachedTokens(v)
	return _u
}

// SetPromptWriteCachedTokens sets the "prompt_write_cached_tokens" field.
func (_u *UsageStatUpdateOne) SetPromptWriteCachedTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetPromptWriteCachedTokens()
	_u.mutation.SetPromptWriteCachedTokens(v)
	return _u
}

// SetNillablePromptWriteCachedTokens sets the "prompt_write_cached_tokens" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillablePromptWriteCachedTokens(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetPromptWriteCachedTokens(*v)
	}
	return _u
}

// AddPromptWriteCachedTokens adds value to the "prompt_write_cached_tokens" field.
func (_u *UsageStatUpdateOne) AddPromptWriteCachedTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.AddPromptWriteCachedTokens(v)
	return _u
}

// SetCompletionReasoningTokens sets the "completion_reasoning_tokens" field.
func (_u *UsageStatUpdateOne) SetCompletionReasoningTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.ResetCompletionReasoningTokens()
	_u.mutation.SetCompletionReasoningTokens(v)
	return _u
}

// SetNillableCompletionReasoningTokens sets the "completion_reasoning_tokens" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillableCompletionReasoningTokens(v *int64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetCompletionReasoningTokens(*v)
	}
	return _u
}

// AddCompletionReasoningTokens adds value to the "completion_reasoning_tokens" field.
func (_u *UsageStatUpdateOne) AddCompletionReasoningTokens(v int64) *UsageStatUpdateOne {
	_u.mutation.AddCompletionReasoningTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *UsageStatUpdateOne) SetTotalCost(v float64) *UsageStatUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *UsageStatUpdateOne) SetNillableTotalCost(v *float64) *UsageStatUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *UsageStatUpdateOne) AddTotalCost(v float64) *UsageStatUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// Mutation returns the UsageStatMutation object of the builder.
func (_u *UsageStatUpdateOne) Mutation() *UsageStatMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageStatUpdate builder.
func (_u *UsageStatUpdateOne) Where(ps ...predicate.UsageStat) *UsageStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageStatUpdateOne) Select(field string, fields ...string) *UsageStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageStat entity.
func (_u *UsageStatUpdateOne) Save(ctx context.Context) (*UsageStat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageStatUpdateOne) SaveX(ctx context.Context) *UsageStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UsageStatUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsageStatUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UsageStatUpdateOne) sqlSave(ctx context.Context) (_node *UsageStat, err error) {
	_spec := sqlgraph.NewUpdateSpec(usagestat.Table, usagestat.Columns, sqlgraph.NewFieldSpec(usagestat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagestat.FieldID)
		for _, f := range fields {
			if !usagestat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagestat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usagestat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usagestat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PromptTokens(); ok {
		_spec.SetField(usagestat.FieldPromptTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPromptTokens(); ok {
		_spec.AddField(usagestat.FieldPromptTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompletionTokens(); ok {
		_spec.SetField(usagestat.FieldCompletionTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletionTokens(); ok {
		_spec.AddField(usagestat.FieldCompletionTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(usagestat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(usagestat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PromptCachedTokens(); ok {
		_spec.SetField(usagestat.FieldPromptCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPromptCachedTokens(); ok {
		_spec.AddField(usagestat.FieldPromptCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PromptWriteCachedTokens(); ok {
		_spec.SetField(usagestat.FieldPromptWriteCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPromptWriteCachedTokens(); ok {
		_spec.AddField(usagestat.FieldPromptWriteCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompletionReasoningTokens(); ok {
		_spec.SetField(usagestat.FieldCompletionReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletionReasoningTokens(); ok {
		_spec.AddField(usagestat.FieldCompletionReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(usagestat.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(usagestat.FieldTotalCost, field.TypeFloat64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UsageStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagestat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
