package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/pkg/xtime"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/samber/lo"
)

// AnalyticsMetadata is the resolver for the analyticsMetadata field.
func (r *queryResolver) AnalyticsMetadata(ctx context.Context) (*AnalyticsMetadata, error) {
	loc := r.systemService.TimeLocation(ctx)

	// Find earliest created_at
	first, err := r.client.UsageLog.Query().Order(ent.Asc(usagelog.FieldCreatedAt)).First(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return &AnalyticsMetadata{}, nil
		}

		return nil, err
	}

	d := first.CreatedAt.In(loc).Format("2006-01-02")
	return &AnalyticsMetadata{EarliestDate: &d}, nil
}

// AnalyticsOverview is the resolver for the analyticsOverview field.
func (r *queryResolver) AnalyticsOverview(ctx context.Context, filter *AnalyticsFilter) (*AnalyticsOverview, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)
	apiKeyIDs, hasUserFilter := r.resolveFilterAPIKeyIDs(ctx, filter)
	loc := r.systemService.TimeLocation(ctx)

	type overviewResult struct {
		TotalRequests     int     `json:"total_requests"`
		TotalInputTokens  int64   `json:"total_input_tokens"`
		TotalCachedTokens int64   `json:"total_cached_tokens"`
		TotalOutputTokens int64   `json:"total_output_tokens"`
		TotalTokens       int64   `json:"total_tokens"`
		TotalCost         float64 `json:"total_cost"`
	}

	var results []overviewResult

	err := r.client.UsageLog.Query().
		Modify(func(s *sql.Selector) {
			r.buildAnalyticsWhere(s, filter, apiKeyIDs, hasUserFilter, loc)

			s.Select(
				sql.As(sql.Count(s.C(usagelog.FieldID)), "total_requests"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptTokens)), "total_input_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptCachedTokens)), "total_cached_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldCompletionTokens)), "total_output_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalTokens)), "total_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalCost)), "total_cost"),
			)
		}).
		Scan(ctx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get analytics overview: %w", err)
	}

	if len(results) == 0 {
		return &AnalyticsOverview{}, nil
	}

	r0 := results[0]

	successCount, failedCount, err := r.queryExecutionSuccessCounts(ctx, filter, apiKeyIDs, hasUserFilter, loc)
	if err != nil {
		return nil, err
	}

	executionTotal := successCount + failedCount
	successRate := 0.0
	if executionTotal > 0 {
		successRate = float64(successCount) / float64(executionTotal) * 100
	}

	return &AnalyticsOverview{
		TotalTokens:              safeIntFromInt64(r0.TotalTokens),
		TotalInputTokens:         safeIntFromInt64(r0.TotalInputTokens),
		TotalCachedInputTokens:   safeIntFromInt64(r0.TotalCachedTokens),
		TotalUncachedInputTokens: safeIntFromInt64(r0.TotalInputTokens - r0.TotalCachedTokens),
		TotalOutputTokens:        safeIntFromInt64(r0.TotalOutputTokens),
		TotalRequests:            r0.TotalRequests,
		TotalCost:                r0.TotalCost,
		FailedRequests:           failedCount,
		SuccessRate:              successRate,
	}, nil
}

// AnalyticsDailyStats is the resolver for the analyticsDailyStats field.
func (r *queryResolver) AnalyticsDailyStats(ctx context.Context, filter *AnalyticsFilter) ([]*AnalyticsDailyStat, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)
	apiKeyIDs, hasUserFilter := r.resolveFilterAPIKeyIDs(ctx, filter)

	loc := r.systemService.TimeLocation(ctx)
	nowUTC := xtime.UTCNow()
	_, offsetSeconds := nowUTC.In(loc).Zone()

	// Determine date range — 同仪表盘 parseTimeWindow 模式
	var startDay, endDay time.Time
	if filter != nil && filter.StartTime != nil {
		startDay = parseDateStr(*filter.StartTime, loc)
	} else {
		// Default: 30 days ago
		nowLocal := nowUTC.In(loc)
		startDay = time.Date(nowLocal.Year(), nowLocal.Month(), nowLocal.Day(), 0, 0, 0, 0, loc)
		startDay = startDay.AddDate(0, 0, -29)
	}

	if filter != nil && filter.EndTime != nil {
		endDay = parseDateStr(*filter.EndTime, loc)
	} else {
		endDay = nowUTC.In(loc)
		endDay = time.Date(endDay.Year(), endDay.Month(), endDay.Day(), 0, 0, 0, 0, loc)
	}

	// 填充缺失日期
	startDay = time.Date(startDay.Year(), startDay.Month(), startDay.Day(), 0, 0, 0, 0, loc)
	endDay = time.Date(endDay.Year(), endDay.Month(), endDay.Day(), 0, 0, 0, 0, loc)

	// Short ranges bucket by hour so a single day still yields a readable curve.
	resolution := resolutionForSpan(int(endDay.Sub(startDay).Hours()/24) + 1)

	type dailyStats struct {
		Date         string  `json:"date"`
		InputTokens  int64   `json:"input_tokens"`
		CachedTokens int64   `json:"cached_tokens"`
		OutputTokens int64   `json:"output_tokens"`
		TotalTokens  int64   `json:"total_tokens"`
		RequestCount int     `json:"request_count"`
		Cost         float64 `json:"cost"`
	}

	var results []dailyStats

	err := r.client.UsageLog.Query().
		Modify(func(s *sql.Selector) {
			r.buildAnalyticsWhere(s, filter, apiKeyIDs, hasUserFilter, loc)

			// Build dialect-specific date expression
			createdAtCol := s.C(usagelog.FieldCreatedAt)
			dateExpr := buildDateExpression(s.Dialect(), createdAtCol, offsetSeconds, loc.String(), resolution)

			s.Select(
				sql.As(dateExpr, "date"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptTokens)), "input_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptCachedTokens)), "cached_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldCompletionTokens)), "output_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalTokens)), "total_tokens"),
				sql.As(sql.Count(s.C(usagelog.FieldID)), "request_count"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalCost)), "cost"),
			).
				GroupBy(dateExpr).
				OrderBy("date")
		}).
		Scan(ctx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get analytics daily stats: %w", err)
	}

	// Build lookup map
	statsMap := lo.SliceToMap(results, func(item dailyStats) (string, dailyStats) {
		return item.Date, item
	})

	// Fill in missing buckets with zero values so the chart's category axis stays evenly
	// spaced: an omitted bucket would pull its neighbours together.
	var response []*AnalyticsDailyStat

	for _, dateStr := range bucketSequence(startDay, endDay.AddDate(0, 0, 1), resolution) {
		stats, exists := statsMap[dateStr]
		if !exists {
			response = append(response, &AnalyticsDailyStat{Date: dateStr})
			continue
		}

		response = append(response, &AnalyticsDailyStat{
			Date:                dateStr,
			InputTokens:         safeIntFromInt64(stats.InputTokens),
			CachedInputTokens:   safeIntFromInt64(stats.CachedTokens),
			UncachedInputTokens: safeIntFromInt64(stats.InputTokens - stats.CachedTokens),
			OutputTokens:        safeIntFromInt64(stats.OutputTokens),
			TotalTokens:         safeIntFromInt64(stats.TotalTokens),
			RequestCount:        stats.RequestCount,
			Cost:                stats.Cost,
		})
	}

	return response, nil
}

// AnalyticsDimensionStats is the resolver for the analyticsDimensionStats field.
func (r *queryResolver) AnalyticsDimensionStats(ctx context.Context, filter *AnalyticsFilter, dimension string) ([]*AnalyticsDimensionStat, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)
	apiKeyIDs, hasUserFilter := r.resolveFilterAPIKeyIDs(ctx, filter)
	loc := r.systemService.TimeLocation(ctx)

	var (
		results []dimStats
		err     error
	)

	switch dimension {
	case "channel":
		results, err = r.queryChannelStats(ctx, filter, apiKeyIDs, hasUserFilter, loc)
	case "model":
		results, err = r.queryModelStats(ctx, filter, apiKeyIDs, hasUserFilter, loc)
	case "apiKey":
		results, err = r.queryAPIKeyStats(ctx, filter, apiKeyIDs, hasUserFilter, loc)
	case "user":
		results, err = r.queryUserStats(ctx, filter, apiKeyIDs, hasUserFilter, loc)
	default:
		return nil, fmt.Errorf("unsupported dimension: %s, must be one of: channel, model, apiKey, user", dimension)
	}

	if err != nil {
		return nil, err
	}

	return dimStatsToDimensionStats(results), nil
}
