package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76-dev

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// AWS is the resolver for the aws field.
func (r *channelCredentialsResolver) AWS(ctx context.Context, obj *objects.ChannelCredentials) (*AWSCredentials, error) {
	panic(fmt.Errorf("not implemented: AWS - aws"))
}

// GCP is the resolver for the gcp field.
func (r *channelCredentialsResolver) GCP(ctx context.Context, obj *objects.ChannelCredentials) (*GCPCredentials, error) {
	panic(fmt.Errorf("not implemented: GCP - gcp"))
}

// CreateChannel is the resolver for the createChannel field.
func (r *mutationResolver) CreateChannel(ctx context.Context, input ent.CreateChannelInput) (*ent.Channel, error) {
	channel, err := r.client.Channel.Create().
		SetType(input.Type).
		SetNillableBaseURL(input.BaseURL).
		SetName(input.Name).
		SetCredentials(input.Credentials).
		SetSupportedModels(input.SupportedModels).
		SetDefaultTestModel(input.DefaultTestModel).
		SetSettings(input.Settings).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create channel: %w", err)
	}

	return channel, nil
}

// UpdateChannel is the resolver for the updateChannel field.
func (r *mutationResolver) UpdateChannel(ctx context.Context, id objects.GUID, input ent.UpdateChannelInput) (*ent.Channel, error) {
	mut := r.client.Channel.UpdateOneID(id.ID).
		SetNillableBaseURL(input.BaseURL).
		SetNillableName(input.Name).
		SetNillableDefaultTestModel(input.DefaultTestModel)

	if input.SupportedModels != nil {
		mut.SetSupportedModels(input.SupportedModels)
	}

	if input.Settings != nil {
		mut.SetSettings(input.Settings)
	}

	if input.Credentials != nil {
		mut.SetCredentials(input.Credentials)
	}

	channel, err := mut.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update channel: %w", err)
	}

	return channel, nil
}

// UpdateChannelStatus is the resolver for the updateChannelStatus field.
func (r *mutationResolver) UpdateChannelStatus(ctx context.Context, id objects.GUID, status channel.Status) (*ent.Channel, error) {
	channel, err := r.client.Channel.UpdateOneID(id.ID).
		SetStatus(status).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update channel status: %w", err)
	}

	return channel, nil
}

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, input ent.CreateAPIKeyInput) (*ent.APIKey, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	// Generate API key with ah- prefix (similar to OpenAI format)
	generatedKey, err := r.authService.GenerateAPIKey()
	if err != nil {
		return nil, fmt.Errorf("failed to generate API key: %w", err)
	}

	apiKey, err := r.client.APIKey.Create().
		SetName(input.Name).
		SetKey(generatedKey).
		SetUserID(user.ID).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create API key: %w", err)
	}

	return apiKey, nil
}

// UpdateAPIKeyStatus is the resolver for the updateAPIKeyStatus field.
func (r *mutationResolver) UpdateAPIKeyStatus(ctx context.Context, id objects.GUID, status apikey.Status) (*ent.APIKey, error) {
	apiKey, err := r.client.APIKey.UpdateOneID(id.ID).
		SetStatus(status).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update API key status: %w", err)
	}

	return apiKey, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	// Hash the password using our auth service
	hashedPassword, err := biz.HashPassword(input.Password)
	if err != nil {
		return nil, err
	}

	mut := r.client.User.Create().
		SetNillableFirstName(input.FirstName).
		SetNillableLastName(input.LastName).
		SetEmail(input.Email).
		SetPassword(hashedPassword).
		SetScopes(input.Scopes)

	if input.RoleIDs != nil {
		mut.AddRoleIDs(input.RoleIDs...)
	}

	user, err := mut.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id objects.GUID, input ent.UpdateUserInput) (*ent.User, error) {
	mut := r.client.User.UpdateOneID(id.ID).
		SetNillableEmail(input.Email).
		SetNillableFirstName(input.FirstName).
		SetNillableLastName(input.LastName).
		SetNillableIsOwner(input.IsOwner)

	if input.Password != nil {
		hashedPassword, err := biz.HashPassword(*input.Password)
		if err != nil {
			return nil, err
		}

		mut.SetPassword(hashedPassword)
	}

	if input.Scopes != nil {
		mut.SetScopes(input.Scopes)
	}

	if input.AppendScopes != nil {
		mut.AppendScopes(input.AppendScopes)
	}

	if input.ClearScopes {
		mut.ClearScopes()
	}

	if input.AddRoleIDs != nil {
		mut.AddRoleIDs(input.AddRoleIDs...)
	}

	if input.RemoveRoleIDs != nil {
		mut.RemoveRoleIDs(input.RemoveRoleIDs...)
	}

	if input.ClearRoles {
		mut.ClearRoles()
	}

	user, err := mut.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return user, nil
}

// UpdateUserStatus is the resolver for the updateUserStatus field.
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, id objects.GUID, status user.Status) (*ent.User, error) {
	user, err := r.client.User.UpdateOneID(id.ID).
		SetStatus(status).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update user status: %w", err)
	}

	return user, nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input ent.CreateRoleInput) (*ent.Role, error) {
	role, err := r.client.Role.Create().
		SetCode(input.Code).
		SetName(input.Name).
		SetScopes(input.Scopes).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create role: %w", err)
	}

	return role, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id objects.GUID, input ent.UpdateRoleInput) (*ent.Role, error) {
	mut := r.client.Role.UpdateOneID(id.ID).
		SetNillableName(input.Name)
	if input.Scopes != nil {
		mut.SetScopes(input.Scopes)
	}

	role, err := mut.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update role: %w", err)
	}

	return role, nil
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input SignInInput) (*SignInPayload, error) {
	// Authenticate user
	user, err := r.authService.AuthenticateUser(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	// Generate JWT token
	token, err := r.authService.GenerateJWTToken(ctx, user)
	if err != nil {
		return nil, err
	}

	return &SignInPayload{
		User:  user,
		Token: token,
	}, nil
}

// InitializeSystem is the resolver for the initializeSystem field.
func (r *mutationResolver) InitializeSystem(ctx context.Context, input InitializeSystemInput) (*InitializeSystemPayload, error) {
	// Check if system is already initialized
	isInitialized, err := r.systemService.IsInitialized(ctx)
	if err != nil {
		return &InitializeSystemPayload{
			Success: false,
			Message: fmt.Sprintf("Failed to check initialization status: %v", err),
		}, nil
	}

	if isInitialized {
		return &InitializeSystemPayload{
			Success: false,
			Message: "System is already initialized",
		}, nil
	}

	err = r.systemService.Initialize(ctx, &biz.InitializeSystemArgs{
		OwnerEmail:     input.OwnerEmail,
		OwnerPassword:  input.OwnerPassword,
		OwnerFirstName: input.OwnerFirstName,
		OwnerLastName:  input.OwnerLastName,
		BrandName:      input.BrandName,
	})
	if err != nil {
		return &InitializeSystemPayload{
			Success: false,
			Message: fmt.Sprintf("Failed to initialize system: %v", err),
		}, nil
	}

	// Generate JWT token for the owner
	token, err := r.SignIn(ctx, SignInInput{
		Email:    input.OwnerEmail,
		Password: input.OwnerPassword,
	})
	if err != nil {
		return &InitializeSystemPayload{
			Success: false,
			Message: fmt.Sprintf("Failed to generate token: %v", err),
		}, nil
	}

	return &InitializeSystemPayload{
		Success: true,
		Message: "System initialized successfully",
		User:    token.User,
		Token:   &token.Token,
	}, nil
}

// UpdateSystemSettings is the resolver for the updateSystemSettings field.
func (r *mutationResolver) UpdateSystemSettings(ctx context.Context, input UpdateSystemSettingsInput) (*SystemSettings, error) {
	if input.StoreChunks != nil {
		err := r.systemService.SetStoreChunks(ctx, *input.StoreChunks)
		if err != nil {
			return nil, fmt.Errorf("failed to update store chunks setting: %w", err)
		}
	}

	if input.BrandName != nil {
		err := r.systemService.SetBrandName(ctx, *input.BrandName)
		if err != nil {
			return nil, fmt.Errorf("failed to update brand name setting: %w", err)
		}
	}

	// Return current settings
	storeChunks, err := r.systemService.StoreChunks(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get store chunks setting: %w", err)
	}

	brandName, err := r.systemService.BrandName(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get brand name setting: %w", err)
	}

	return &SystemSettings{
		StoreChunks: storeChunks,
		BrandName:   &brandName,
	}, nil
}

// SystemStatus is the resolver for the systemStatus field.
func (r *queryResolver) SystemStatus(ctx context.Context) (*SystemStatus, error) {
	isInitialized, err := r.systemService.IsInitialized(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to check initialization status: %w", err)
	}

	return &SystemStatus{
		IsInitialized: isInitialized,
	}, nil
}

// SystemSettings is the resolver for the systemSettings field.
func (r *queryResolver) SystemSettings(ctx context.Context) (*SystemSettings, error) {
	storeChunks, err := r.systemService.StoreChunks(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get store chunks setting: %w", err)
	}

	brandName, err := r.systemService.BrandName(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get brand name setting: %w", err)
	}

	return &SystemSettings{
		StoreChunks: storeChunks,
		BrandName:   &brandName,
	}, nil
}

// AWS is the resolver for the aws field.
func (r *channelCredentialsInputResolver) AWS(ctx context.Context, obj *objects.ChannelCredentials, data *AWSCredentialsInput) error {
	panic(fmt.Errorf("not implemented: AWS - aws"))
}

// GCP is the resolver for the gcp field.
func (r *channelCredentialsInputResolver) GCP(ctx context.Context, obj *objects.ChannelCredentials, data *GCPCredentialsInput) error {
	panic(fmt.Errorf("not implemented: GCP - gcp"))
}

// ChannelCredentials returns ChannelCredentialsResolver implementation.
func (r *Resolver) ChannelCredentials() ChannelCredentialsResolver {
	return &channelCredentialsResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// ChannelCredentialsInput returns ChannelCredentialsInputResolver implementation.
func (r *Resolver) ChannelCredentialsInput() ChannelCredentialsInputResolver {
	return &channelCredentialsInputResolver{r}
}

type (
	channelCredentialsResolver      struct{ *Resolver }
	mutationResolver                struct{ *Resolver }
	channelCredentialsInputResolver struct{ *Resolver }
)
