package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78-dev

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/samber/lo"
)

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input UpdateMeInput) (*ent.User, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	// Update user fields
	mut := r.client.User.UpdateOneID(user.ID)

	if input.Email != nil {
		mut.SetEmail(*input.Email)
	}

	if input.FirstName != nil {
		mut.SetFirstName(*input.FirstName)
	}

	if input.LastName != nil {
		mut.SetLastName(*input.LastName)
	}

	if input.PreferLanguage != nil {
		mut.SetPreferLanguage(*input.PreferLanguage)
	}

	if input.Avatar != nil {
		mut.SetAvatar(*input.Avatar)
	}

	return mut.Save(ctx)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*UserInfo, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	// Convert ent.Role to RoleInfo
	userRoles := make([]*RoleInfo, len(user.Edges.Roles))
	for i, role := range user.Edges.Roles {
		userRoles[i] = &RoleInfo{
			Code: role.Code,
			Name: role.Name,
		}
	}

	// Calculate all scopes (user scopes + role scopes)
	allScopes := make(map[string]bool)

	// Add user's direct scopes
	for _, scope := range user.Scopes {
		allScopes[scope] = true
	}

	// Add scopes from all roles
	for _, role := range user.Edges.Roles {
		for _, scope := range role.Scopes {
			allScopes[scope] = true
		}
	}

	return &UserInfo{
		Email:          user.Email,
		FirstName:      user.FirstName,
		LastName:       user.LastName,
		IsOwner:        user.IsOwner,
		PreferLanguage: user.PreferLanguage,
		Avatar:         &user.Avatar,
		Scopes:         lo.Keys(allScopes),
		Roles:          userRoles,
	}, nil
}
