// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

type AddUserToProjectInput struct {
	ProjectID objects.GUID    `json:"projectId"`
	UserID    objects.GUID    `json:"userId"`
	IsOwner   *bool           `json:"isOwner,omitempty"`
	Scopes    []string        `json:"scopes,omitempty"`
	RoleIDs   []*objects.GUID `json:"roleIDs,omitempty"`
}

type BrandSettings struct {
	BrandName *string `json:"brandName,omitempty"`
	BrandLogo *string `json:"brandLogo,omitempty"`
}

type BulkImportChannelsInput struct {
	Channels []*biz.BulkImportChannelItem `json:"channels"`
}

type BulkUpdateChannelOrderingInput struct {
	Channels []*biz.ChannelOrderingItem `json:"channels"`
}

type BulkUpdateChannelOrderingResult struct {
	Success  bool           `json:"success"`
	Updated  int            `json:"updated"`
	Channels []*ent.Channel `json:"channels"`
}

type ChannelTypeCount struct {
	Type  string `json:"type"`
	Count int    `json:"count"`
}

type CountChannelsByTypeInput struct {
	// Filtering options for Channels returned from the connection.
	StatusIn []channel.Status `json:"statusIn,omitempty"`
}

type DailyRequestStats struct {
	Date  string `json:"date"`
	Count int    `json:"count"`
}

type DashboardOverview struct {
	TotalUsers          int           `json:"totalUsers"`
	TotalRequests       int           `json:"totalRequests"`
	RequestStats        *RequestStats `json:"requestStats"`
	FailedRequests      int           `json:"failedRequests"`
	AverageResponseTime *float64      `json:"averageResponseTime,omitempty"`
}

type FetchModelsPayload struct {
	Models []*objects.ModelIdentify `json:"models"`
	Error  *string                  `json:"error,omitempty"`
}

type HourlyRequestStats struct {
	Hour  int `json:"hour"`
	Count int `json:"count"`
}

type InitializeSystemInput struct {
	OwnerEmail     string `json:"ownerEmail"`
	OwnerPassword  string `json:"ownerPassword"`
	OwnerFirstName string `json:"ownerFirstName"`
	OwnerLastName  string `json:"ownerLastName"`
	BrandName      string `json:"brandName"`
}

type InitializeSystemPayload struct {
	Success bool      `json:"success"`
	Message string    `json:"message"`
	User    *ent.User `json:"user,omitempty"`
	Token   *string   `json:"token,omitempty"`
}

type ModelsInput struct {
	StatusIn       []channel.Status `json:"statusIn,omitempty"`
	IncludeMapping *bool            `json:"includeMapping,omitempty"`
	IncludePrefix  *bool            `json:"includePrefix,omitempty"`
}

type RemoveUserFromProjectInput struct {
	ProjectID objects.GUID `json:"projectId"`
	UserID    objects.GUID `json:"userId"`
}

type RequestStats struct {
	RequestsToday     int `json:"requestsToday"`
	RequestsThisWeek  int `json:"requestsThisWeek"`
	RequestsThisMonth int `json:"requestsThisMonth"`
}

type RequestStatsByChannel struct {
	ChannelName string `json:"channelName"`
	ChannelType string `json:"channelType"`
	Count       int    `json:"count"`
}

type RequestStatsByModel struct {
	ModelID string `json:"modelId"`
	Count   int    `json:"count"`
}

type ScopeInfo struct {
	Scope       string   `json:"scope"`
	Description string   `json:"description"`
	Levels      []string `json:"levels"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInPayload struct {
	User  *ent.User `json:"user"`
	Token string    `json:"token"`
}

type SystemStatus struct {
	IsInitialized bool `json:"isInitialized"`
}

type TestChannelInput struct {
	ChannelID objects.GUID         `json:"channelID"`
	ModelID   *string              `json:"modelID,omitempty"`
	Proxy     *objects.ProxyConfig `json:"proxy,omitempty"`
}

type TestChannelPayload struct {
	Latency float64 `json:"latency"`
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type TokenStats struct {
	TotalInputTokensToday      int `json:"totalInputTokensToday"`
	TotalOutputTokensToday     int `json:"totalOutputTokensToday"`
	TotalCachedTokensToday     int `json:"totalCachedTokensToday"`
	TotalInputTokensThisWeek   int `json:"totalInputTokensThisWeek"`
	TotalOutputTokensThisWeek  int `json:"totalOutputTokensThisWeek"`
	TotalCachedTokensThisWeek  int `json:"totalCachedTokensThisWeek"`
	TotalInputTokensThisMonth  int `json:"totalInputTokensThisMonth"`
	TotalOutputTokensThisMonth int `json:"totalOutputTokensThisMonth"`
	TotalCachedTokensThisMonth int `json:"totalCachedTokensThisMonth"`
}

type TopRequestsProjects struct {
	ProjectID          objects.GUID `json:"projectId"`
	ProjectName        string       `json:"projectName"`
	ProjectDescription string       `json:"projectDescription"`
	RequestCount       int          `json:"requestCount"`
}

type UpdateBrandSettingsInput struct {
	BrandName *string `json:"brandName,omitempty"`
	BrandLogo *string `json:"brandLogo,omitempty"`
}

type UpdateDefaultDataStorageInput struct {
	DataStorageID objects.GUID `json:"dataStorageID"`
}

type UpdateMeInput struct {
	Email          *string `json:"email,omitempty"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	PreferLanguage *string `json:"preferLanguage,omitempty"`
	Avatar         *string `json:"avatar,omitempty"`
}

type UpdateProjectUserInput struct {
	ProjectID     objects.GUID    `json:"projectId"`
	UserID        objects.GUID    `json:"userId"`
	IsOwner       *bool           `json:"isOwner,omitempty"`
	Scopes        []string        `json:"scopes,omitempty"`
	AddRoleIDs    []*objects.GUID `json:"addRoleIDs,omitempty"`
	RemoveRoleIDs []*objects.GUID `json:"removeRoleIDs,omitempty"`
}
