// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/objects"
)

type AddUserToProjectInput struct {
	ProjectID objects.GUID    `json:"projectId"`
	UserID    objects.GUID    `json:"userId"`
	IsOwner   *bool           `json:"isOwner,omitempty"`
	Scopes    []string        `json:"scopes,omitempty"`
	RoleIDs   []*objects.GUID `json:"roleIDs,omitempty"`
}

type BrandSettings struct {
	BrandName *string `json:"brandName,omitempty"`
	BrandLogo *string `json:"brandLogo,omitempty"`
}

type BulkImportChannelItem struct {
	Type             string   `json:"type"`
	Name             string   `json:"name"`
	BaseURL          *string  `json:"baseURL,omitempty"`
	APIKey           *string  `json:"apiKey,omitempty"`
	SupportedModels  []string `json:"supportedModels"`
	DefaultTestModel string   `json:"defaultTestModel"`
}

type BulkImportChannelsInput struct {
	Channels []*BulkImportChannelItem `json:"channels"`
}

type BulkImportChannelsResult struct {
	Success  bool           `json:"success"`
	Created  int            `json:"created"`
	Failed   int            `json:"failed"`
	Errors   []string       `json:"errors,omitempty"`
	Channels []*ent.Channel `json:"channels"`
}

type BulkUpdateChannelOrderingInput struct {
	Channels []*ChannelOrderingItem `json:"channels"`
}

type BulkUpdateChannelOrderingResult struct {
	Success  bool           `json:"success"`
	Updated  int            `json:"updated"`
	Channels []*ent.Channel `json:"channels"`
}

type ChannelOrderingItem struct {
	ID             objects.GUID `json:"id"`
	OrderingWeight int          `json:"orderingWeight"`
}

type DailyRequestStats struct {
	Date  string `json:"date"`
	Count int    `json:"count"`
}

type DashboardOverview struct {
	TotalUsers          int           `json:"totalUsers"`
	TotalRequests       int           `json:"totalRequests"`
	RequestStats        *RequestStats `json:"requestStats"`
	FailedRequests      int           `json:"failedRequests"`
	AverageResponseTime *float64      `json:"averageResponseTime,omitempty"`
}

type FetchModelsInput struct {
	ChannelType string        `json:"channelType"`
	BaseURL     string        `json:"baseURL"`
	APIKey      *string       `json:"apiKey,omitempty"`
	ChannelID   *objects.GUID `json:"channelID,omitempty"`
}

type FetchModelsPayload struct {
	Models []*objects.ModelIdentify `json:"models"`
	Error  *string                  `json:"error,omitempty"`
}

type Gcs struct {
	BucketName string                 `json:"bucketName"`
	Credential *objects.GCPCredential `json:"credential"`
}

type GCSInput struct {
	BucketName string                 `json:"bucketName"`
	Credential *objects.GCPCredential `json:"credential"`
}

type HourlyRequestStats struct {
	Hour  int `json:"hour"`
	Count int `json:"count"`
}

type InitializeSystemInput struct {
	OwnerEmail     string `json:"ownerEmail"`
	OwnerPassword  string `json:"ownerPassword"`
	OwnerFirstName string `json:"ownerFirstName"`
	OwnerLastName  string `json:"ownerLastName"`
	BrandName      string `json:"brandName"`
}

type InitializeSystemPayload struct {
	Success bool      `json:"success"`
	Message string    `json:"message"`
	User    *ent.User `json:"user,omitempty"`
	Token   *string   `json:"token,omitempty"`
}

type Model struct {
	ID     string         `json:"id"`
	Status channel.Status `json:"status"`
}

type ModelsInput struct {
	Status *channel.Status `json:"status,omitempty"`
}

type RemoveUserFromProjectInput struct {
	ProjectID objects.GUID `json:"projectId"`
	UserID    objects.GUID `json:"userId"`
}

type RequestStats struct {
	RequestsToday     int `json:"requestsToday"`
	RequestsThisWeek  int `json:"requestsThisWeek"`
	RequestsThisMonth int `json:"requestsThisMonth"`
}

type RequestStatsByChannel struct {
	ChannelName string `json:"channelName"`
	ChannelType string `json:"channelType"`
	Count       int    `json:"count"`
}

type RequestStatsByModel struct {
	ModelID string `json:"modelId"`
	Count   int    `json:"count"`
}

type S3 struct {
	BucketName string `json:"bucketName"`
	Endpoint   string `json:"endpoint"`
	AccessKey  string `json:"accessKey"`
	SecretKey  string `json:"secretKey"`
}

type S3Input struct {
	BucketName string `json:"bucketName"`
	Endpoint   string `json:"endpoint"`
	AccessKey  string `json:"accessKey"`
	SecretKey  string `json:"secretKey"`
}

type ScopeInfo struct {
	Scope       string   `json:"scope"`
	Description string   `json:"description"`
	Levels      []string `json:"levels"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInPayload struct {
	User  *ent.User `json:"user"`
	Token string    `json:"token"`
}

type SystemStatus struct {
	IsInitialized bool `json:"isInitialized"`
}

type TestChannelInput struct {
	ChannelID objects.GUID `json:"channelID"`
	ModelID   *string      `json:"modelID,omitempty"`
}

type TestChannelPayload struct {
	Latency float64 `json:"latency"`
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type TokenStats struct {
	TotalInputTokensToday      int `json:"totalInputTokensToday"`
	TotalOutputTokensToday     int `json:"totalOutputTokensToday"`
	TotalCachedTokensToday     int `json:"totalCachedTokensToday"`
	TotalInputTokensThisWeek   int `json:"totalInputTokensThisWeek"`
	TotalOutputTokensThisWeek  int `json:"totalOutputTokensThisWeek"`
	TotalCachedTokensThisWeek  int `json:"totalCachedTokensThisWeek"`
	TotalInputTokensThisMonth  int `json:"totalInputTokensThisMonth"`
	TotalOutputTokensThisMonth int `json:"totalOutputTokensThisMonth"`
	TotalCachedTokensThisMonth int `json:"totalCachedTokensThisMonth"`
}

type TopRequestsProjects struct {
	ProjectID          objects.GUID `json:"projectId"`
	ProjectName        string       `json:"projectName"`
	ProjectDescription string       `json:"projectDescription"`
	RequestCount       int          `json:"requestCount"`
}

type UpdateBrandSettingsInput struct {
	BrandName *string `json:"brandName,omitempty"`
	BrandLogo *string `json:"brandLogo,omitempty"`
}

type UpdateMeInput struct {
	Email          *string `json:"email,omitempty"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	PreferLanguage *string `json:"preferLanguage,omitempty"`
	Avatar         *string `json:"avatar,omitempty"`
}

type UpdateProjectUserInput struct {
	ProjectID     objects.GUID    `json:"projectId"`
	UserID        objects.GUID    `json:"userId"`
	IsOwner       *bool           `json:"isOwner,omitempty"`
	Scopes        []string        `json:"scopes,omitempty"`
	AddRoleIDs    []*objects.GUID `json:"addRoleIDs,omitempty"`
	RemoveRoleIDs []*objects.GUID `json:"removeRoleIDs,omitempty"`
}
