// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

import (
	"github.com/looplj/axonhub/objects"
)

type DailyRequestStats struct {
	Date         string `json:"date"`
	Count        int    `json:"count"`
	SuccessCount int    `json:"successCount"`
	FailedCount  int    `json:"failedCount"`
}

type DashboardStats struct {
	TotalUsers          int      `json:"totalUsers"`
	TotalChannels       int      `json:"totalChannels"`
	TotalRequests       int      `json:"totalRequests"`
	TotalAPIKeys        int      `json:"totalAPIKeys"`
	RequestsToday       int      `json:"requestsToday"`
	RequestsThisWeek    int      `json:"requestsThisWeek"`
	RequestsThisMonth   int      `json:"requestsThisMonth"`
	SuccessfulRequests  int      `json:"successfulRequests"`
	FailedRequests      int      `json:"failedRequests"`
	AverageResponseTime *float64 `json:"averageResponseTime,omitempty"`
}

type HourlyRequestStats struct {
	Hour  int `json:"hour"`
	Count int `json:"count"`
}

type RequestsByChannel struct {
	ChannelName string `json:"channelName"`
	ChannelType string `json:"channelType"`
	Count       int    `json:"count"`
}

type RequestsByModel struct {
	ModelID string `json:"modelId"`
	Count   int    `json:"count"`
}

type RequestsByStatus struct {
	Status string `json:"status"`
	Count  int    `json:"count"`
}

type ScopeInfo struct {
	Scope       string `json:"scope"`
	Description string `json:"description"`
}

type TopUsers struct {
	UserID       objects.GUID `json:"userId"`
	UserName     string       `json:"userName"`
	UserEmail    string       `json:"userEmail"`
	RequestCount int          `json:"requestCount"`
}
