// Code generated by ent, DO NOT EDIT.

package channelclientid

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLTE(FieldID, id))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldChannelID, v))
}

// PrincipalKind applies equality check predicate on the "principal_kind" field. It's identical to PrincipalKindEQ.
func PrincipalKind(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldPrincipalKind, v))
}

// PrincipalHash applies equality check predicate on the "principal_hash" field. It's identical to PrincipalHashEQ.
func PrincipalHash(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldPrincipalHash, v))
}

// ClientIDHex applies equality check predicate on the "client_id_hex" field. It's identical to ClientIDHexEQ.
func ClientIDHex(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldClientIDHex, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldCreatedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLTE(FieldChannelID, v))
}

// PrincipalKindEQ applies the EQ predicate on the "principal_kind" field.
func PrincipalKindEQ(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldPrincipalKind, v))
}

// PrincipalKindNEQ applies the NEQ predicate on the "principal_kind" field.
func PrincipalKindNEQ(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNEQ(FieldPrincipalKind, v))
}

// PrincipalKindIn applies the In predicate on the "principal_kind" field.
func PrincipalKindIn(vs ...string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldIn(FieldPrincipalKind, vs...))
}

// PrincipalKindNotIn applies the NotIn predicate on the "principal_kind" field.
func PrincipalKindNotIn(vs ...string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNotIn(FieldPrincipalKind, vs...))
}

// PrincipalKindGT applies the GT predicate on the "principal_kind" field.
func PrincipalKindGT(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGT(FieldPrincipalKind, v))
}

// PrincipalKindGTE applies the GTE predicate on the "principal_kind" field.
func PrincipalKindGTE(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGTE(FieldPrincipalKind, v))
}

// PrincipalKindLT applies the LT predicate on the "principal_kind" field.
func PrincipalKindLT(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLT(FieldPrincipalKind, v))
}

// PrincipalKindLTE applies the LTE predicate on the "principal_kind" field.
func PrincipalKindLTE(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLTE(FieldPrincipalKind, v))
}

// PrincipalKindContains applies the Contains predicate on the "principal_kind" field.
func PrincipalKindContains(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldContains(FieldPrincipalKind, v))
}

// PrincipalKindHasPrefix applies the HasPrefix predicate on the "principal_kind" field.
func PrincipalKindHasPrefix(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldHasPrefix(FieldPrincipalKind, v))
}

// PrincipalKindHasSuffix applies the HasSuffix predicate on the "principal_kind" field.
func PrincipalKindHasSuffix(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldHasSuffix(FieldPrincipalKind, v))
}

// PrincipalKindEqualFold applies the EqualFold predicate on the "principal_kind" field.
func PrincipalKindEqualFold(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEqualFold(FieldPrincipalKind, v))
}

// PrincipalKindContainsFold applies the ContainsFold predicate on the "principal_kind" field.
func PrincipalKindContainsFold(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldContainsFold(FieldPrincipalKind, v))
}

// PrincipalHashEQ applies the EQ predicate on the "principal_hash" field.
func PrincipalHashEQ(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldPrincipalHash, v))
}

// PrincipalHashNEQ applies the NEQ predicate on the "principal_hash" field.
func PrincipalHashNEQ(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNEQ(FieldPrincipalHash, v))
}

// PrincipalHashIn applies the In predicate on the "principal_hash" field.
func PrincipalHashIn(vs ...string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldIn(FieldPrincipalHash, vs...))
}

// PrincipalHashNotIn applies the NotIn predicate on the "principal_hash" field.
func PrincipalHashNotIn(vs ...string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNotIn(FieldPrincipalHash, vs...))
}

// PrincipalHashGT applies the GT predicate on the "principal_hash" field.
func PrincipalHashGT(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGT(FieldPrincipalHash, v))
}

// PrincipalHashGTE applies the GTE predicate on the "principal_hash" field.
func PrincipalHashGTE(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGTE(FieldPrincipalHash, v))
}

// PrincipalHashLT applies the LT predicate on the "principal_hash" field.
func PrincipalHashLT(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLT(FieldPrincipalHash, v))
}

// PrincipalHashLTE applies the LTE predicate on the "principal_hash" field.
func PrincipalHashLTE(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLTE(FieldPrincipalHash, v))
}

// PrincipalHashContains applies the Contains predicate on the "principal_hash" field.
func PrincipalHashContains(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldContains(FieldPrincipalHash, v))
}

// PrincipalHashHasPrefix applies the HasPrefix predicate on the "principal_hash" field.
func PrincipalHashHasPrefix(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldHasPrefix(FieldPrincipalHash, v))
}

// PrincipalHashHasSuffix applies the HasSuffix predicate on the "principal_hash" field.
func PrincipalHashHasSuffix(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldHasSuffix(FieldPrincipalHash, v))
}

// PrincipalHashEqualFold applies the EqualFold predicate on the "principal_hash" field.
func PrincipalHashEqualFold(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEqualFold(FieldPrincipalHash, v))
}

// PrincipalHashContainsFold applies the ContainsFold predicate on the "principal_hash" field.
func PrincipalHashContainsFold(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldContainsFold(FieldPrincipalHash, v))
}

// ClientIDHexEQ applies the EQ predicate on the "client_id_hex" field.
func ClientIDHexEQ(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldClientIDHex, v))
}

// ClientIDHexNEQ applies the NEQ predicate on the "client_id_hex" field.
func ClientIDHexNEQ(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNEQ(FieldClientIDHex, v))
}

// ClientIDHexIn applies the In predicate on the "client_id_hex" field.
func ClientIDHexIn(vs ...string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldIn(FieldClientIDHex, vs...))
}

// ClientIDHexNotIn applies the NotIn predicate on the "client_id_hex" field.
func ClientIDHexNotIn(vs ...string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNotIn(FieldClientIDHex, vs...))
}

// ClientIDHexGT applies the GT predicate on the "client_id_hex" field.
func ClientIDHexGT(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGT(FieldClientIDHex, v))
}

// ClientIDHexGTE applies the GTE predicate on the "client_id_hex" field.
func ClientIDHexGTE(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGTE(FieldClientIDHex, v))
}

// ClientIDHexLT applies the LT predicate on the "client_id_hex" field.
func ClientIDHexLT(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLT(FieldClientIDHex, v))
}

// ClientIDHexLTE applies the LTE predicate on the "client_id_hex" field.
func ClientIDHexLTE(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLTE(FieldClientIDHex, v))
}

// ClientIDHexContains applies the Contains predicate on the "client_id_hex" field.
func ClientIDHexContains(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldContains(FieldClientIDHex, v))
}

// ClientIDHexHasPrefix applies the HasPrefix predicate on the "client_id_hex" field.
func ClientIDHexHasPrefix(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldHasPrefix(FieldClientIDHex, v))
}

// ClientIDHexHasSuffix applies the HasSuffix predicate on the "client_id_hex" field.
func ClientIDHexHasSuffix(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldHasSuffix(FieldClientIDHex, v))
}

// ClientIDHexEqualFold applies the EqualFold predicate on the "client_id_hex" field.
func ClientIDHexEqualFold(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEqualFold(FieldClientIDHex, v))
}

// ClientIDHexContainsFold applies the ContainsFold predicate on the "client_id_hex" field.
func ClientIDHexContainsFold(v string) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldContainsFold(FieldClientIDHex, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelClientID) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelClientID) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelClientID) predicate.ChannelClientID {
	return predicate.ChannelClientID(sql.NotPredicates(p))
}
