// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

type AckAgentMessagesInput struct {
	InstanceID string   `json:"instanceID"`
	MessageIDs []string `json:"messageIDs"`
}

// GetInstanceID returns AckAgentMessagesInput.InstanceID, and is useful for accessing the field via an interface.
func (v *AckAgentMessagesInput) GetInstanceID() string { return v.InstanceID }

// GetMessageIDs returns AckAgentMessagesInput.MessageIDs, and is useful for accessing the field via an interface.
func (v *AckAgentMessagesInput) GetMessageIDs() []string { return v.MessageIDs }

// AckAgentMessagesResponse is returned by AckAgentMessages on success.
type AckAgentMessagesResponse struct {
	AckAgentMessages bool `json:"ackAgentMessages"`
}

// GetAckAgentMessages returns AckAgentMessagesResponse.AckAgentMessages, and is useful for accessing the field via an interface.
func (v *AckAgentMessagesResponse) GetAckAgentMessages() bool { return v.AckAgentMessages }

// AgentBootstrapAgentBootstrap includes the requested fields of the GraphQL type AgentBootstrap.
type AgentBootstrapAgentBootstrap struct {
	AgentID      string                                                      `json:"agentID"`
	AgentName    string                                                      `json:"agentName"`
	Model        *string                                                     `json:"model"`
	SystemPrompt string                                                      `json:"systemPrompt"`
	Tools        []*AgentBootstrapAgentBootstrapToolsAgentToolDefinition     `json:"tools"`
	Skills       []*AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition   `json:"skills"`
	BuiltinTools []*AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool `json:"builtinTools"`
}

// GetAgentID returns AgentBootstrapAgentBootstrap.AgentID, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetAgentID() string { return v.AgentID }

// GetAgentName returns AgentBootstrapAgentBootstrap.AgentName, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetAgentName() string { return v.AgentName }

// GetModel returns AgentBootstrapAgentBootstrap.Model, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetModel() *string { return v.Model }

// GetSystemPrompt returns AgentBootstrapAgentBootstrap.SystemPrompt, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetSystemPrompt() string { return v.SystemPrompt }

// GetTools returns AgentBootstrapAgentBootstrap.Tools, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetTools() []*AgentBootstrapAgentBootstrapToolsAgentToolDefinition {
	return v.Tools
}

// GetSkills returns AgentBootstrapAgentBootstrap.Skills, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetSkills() []*AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition {
	return v.Skills
}

// GetBuiltinTools returns AgentBootstrapAgentBootstrap.BuiltinTools, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrap) GetBuiltinTools() []*AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool {
	return v.BuiltinTools
}

// AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool includes the requested fields of the GraphQL type AgentBuiltinTool.
type AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool struct {
	Name    string           `json:"name"`
	Enabled bool             `json:"enabled"`
	Order   int              `json:"order"`
	Config  *json.RawMessage `json:"config"`
}

// GetName returns AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool.Name, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool) GetName() string { return v.Name }

// GetEnabled returns AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool.Enabled, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool) GetEnabled() bool {
	return v.Enabled
}

// GetOrder returns AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool.Order, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool) GetOrder() int { return v.Order }

// GetConfig returns AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool.Config, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapBuiltinToolsAgentBuiltinTool) GetConfig() *json.RawMessage {
	return v.Config
}

// AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition includes the requested fields of the GraphQL type AgentSkillDefinition.
type AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition struct {
	Name       string  `json:"name"`
	Content    *string `json:"content"`
	Entrypoint *string `json:"entrypoint"`
	Args       *string `json:"args"`
}

// GetName returns AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition.Name, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition) GetName() string { return v.Name }

// GetContent returns AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition.Content, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition) GetContent() *string {
	return v.Content
}

// GetEntrypoint returns AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition.Entrypoint, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition) GetEntrypoint() *string {
	return v.Entrypoint
}

// GetArgs returns AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition.Args, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapSkillsAgentSkillDefinition) GetArgs() *string { return v.Args }

// AgentBootstrapAgentBootstrapToolsAgentToolDefinition includes the requested fields of the GraphQL type AgentToolDefinition.
type AgentBootstrapAgentBootstrapToolsAgentToolDefinition struct {
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Parameters  json.RawMessage  `json:"parameters"`
	Config      *json.RawMessage `json:"config"`
}

// GetName returns AgentBootstrapAgentBootstrapToolsAgentToolDefinition.Name, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapToolsAgentToolDefinition) GetName() string { return v.Name }

// GetDescription returns AgentBootstrapAgentBootstrapToolsAgentToolDefinition.Description, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapToolsAgentToolDefinition) GetDescription() string {
	return v.Description
}

// GetParameters returns AgentBootstrapAgentBootstrapToolsAgentToolDefinition.Parameters, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapToolsAgentToolDefinition) GetParameters() json.RawMessage {
	return v.Parameters
}

// GetConfig returns AgentBootstrapAgentBootstrapToolsAgentToolDefinition.Config, and is useful for accessing the field via an interface.
func (v *AgentBootstrapAgentBootstrapToolsAgentToolDefinition) GetConfig() *json.RawMessage {
	return v.Config
}

// AgentBootstrapResponse is returned by AgentBootstrap on success.
type AgentBootstrapResponse struct {
	AgentBootstrap *AgentBootstrapAgentBootstrap `json:"agentBootstrap"`
}

// GetAgentBootstrap returns AgentBootstrapResponse.AgentBootstrap, and is useful for accessing the field via an interface.
func (v *AgentBootstrapResponse) GetAgentBootstrap() *AgentBootstrapAgentBootstrap {
	return v.AgentBootstrap
}

type HeartbeatAgentInstanceInput struct {
	InstanceID string `json:"instanceID"`
}

// GetInstanceID returns HeartbeatAgentInstanceInput.InstanceID, and is useful for accessing the field via an interface.
func (v *HeartbeatAgentInstanceInput) GetInstanceID() string { return v.InstanceID }

// HeartbeatAgentInstanceResponse is returned by HeartbeatAgentInstance on success.
type HeartbeatAgentInstanceResponse struct {
	HeartbeatAgentInstance bool `json:"heartbeatAgentInstance"`
}

// GetHeartbeatAgentInstance returns HeartbeatAgentInstanceResponse.HeartbeatAgentInstance, and is useful for accessing the field via an interface.
func (v *HeartbeatAgentInstanceResponse) GetHeartbeatAgentInstance() bool {
	return v.HeartbeatAgentInstance
}

type PullAgentMessagesInput struct {
	InstanceID    string `json:"instanceID"`
	ThreadID      string `json:"threadID"`
	AfterSequence *int   `json:"afterSequence"`
	Limit         *int   `json:"limit"`
}

// GetInstanceID returns PullAgentMessagesInput.InstanceID, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesInput) GetInstanceID() string { return v.InstanceID }

// GetThreadID returns PullAgentMessagesInput.ThreadID, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesInput) GetThreadID() string { return v.ThreadID }

// GetAfterSequence returns PullAgentMessagesInput.AfterSequence, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesInput) GetAfterSequence() *int { return v.AfterSequence }

// GetLimit returns PullAgentMessagesInput.Limit, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesInput) GetLimit() *int { return v.Limit }

// PullAgentMessagesPullAgentMessagesAgentMessage includes the requested fields of the GraphQL type AgentMessage.
type PullAgentMessagesPullAgentMessagesAgentMessage struct {
	Id       string `json:"id"`
	ThreadID string `json:"threadID"`
	Text     string `json:"text"`
	Sequence int    `json:"sequence"`
}

// GetId returns PullAgentMessagesPullAgentMessagesAgentMessage.Id, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesPullAgentMessagesAgentMessage) GetId() string { return v.Id }

// GetThreadID returns PullAgentMessagesPullAgentMessagesAgentMessage.ThreadID, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesPullAgentMessagesAgentMessage) GetThreadID() string { return v.ThreadID }

// GetText returns PullAgentMessagesPullAgentMessagesAgentMessage.Text, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesPullAgentMessagesAgentMessage) GetText() string { return v.Text }

// GetSequence returns PullAgentMessagesPullAgentMessagesAgentMessage.Sequence, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesPullAgentMessagesAgentMessage) GetSequence() int { return v.Sequence }

// PullAgentMessagesResponse is returned by PullAgentMessages on success.
type PullAgentMessagesResponse struct {
	PullAgentMessages []*PullAgentMessagesPullAgentMessagesAgentMessage `json:"pullAgentMessages"`
}

// GetPullAgentMessages returns PullAgentMessagesResponse.PullAgentMessages, and is useful for accessing the field via an interface.
func (v *PullAgentMessagesResponse) GetPullAgentMessages() []*PullAgentMessagesPullAgentMessagesAgentMessage {
	return v.PullAgentMessages
}

type PushAgentMessageInput struct {
	InstanceID string `json:"instanceID"`
	ThreadID   string `json:"threadID"`
	Text       string `json:"text"`
}

// GetInstanceID returns PushAgentMessageInput.InstanceID, and is useful for accessing the field via an interface.
func (v *PushAgentMessageInput) GetInstanceID() string { return v.InstanceID }

// GetThreadID returns PushAgentMessageInput.ThreadID, and is useful for accessing the field via an interface.
func (v *PushAgentMessageInput) GetThreadID() string { return v.ThreadID }

// GetText returns PushAgentMessageInput.Text, and is useful for accessing the field via an interface.
func (v *PushAgentMessageInput) GetText() string { return v.Text }

// PushAgentMessagePushAgentMessage includes the requested fields of the GraphQL type AgentMessage.
type PushAgentMessagePushAgentMessage struct {
	Id string `json:"id"`
}

// GetId returns PushAgentMessagePushAgentMessage.Id, and is useful for accessing the field via an interface.
func (v *PushAgentMessagePushAgentMessage) GetId() string { return v.Id }

// PushAgentMessageResponse is returned by PushAgentMessage on success.
type PushAgentMessageResponse struct {
	PushAgentMessage *PushAgentMessagePushAgentMessage `json:"pushAgentMessage"`
}

// GetPushAgentMessage returns PushAgentMessageResponse.PushAgentMessage, and is useful for accessing the field via an interface.
func (v *PushAgentMessageResponse) GetPushAgentMessage() *PushAgentMessagePushAgentMessage {
	return v.PushAgentMessage
}

type RegisterAgentInstanceInput struct {
	InstanceID string  `json:"instanceID"`
	Name       *string `json:"name"`
	Platform   *string `json:"platform"`
	Version    *string `json:"version"`
}

// GetInstanceID returns RegisterAgentInstanceInput.InstanceID, and is useful for accessing the field via an interface.
func (v *RegisterAgentInstanceInput) GetInstanceID() string { return v.InstanceID }

// GetName returns RegisterAgentInstanceInput.Name, and is useful for accessing the field via an interface.
func (v *RegisterAgentInstanceInput) GetName() *string { return v.Name }

// GetPlatform returns RegisterAgentInstanceInput.Platform, and is useful for accessing the field via an interface.
func (v *RegisterAgentInstanceInput) GetPlatform() *string { return v.Platform }

// GetVersion returns RegisterAgentInstanceInput.Version, and is useful for accessing the field via an interface.
func (v *RegisterAgentInstanceInput) GetVersion() *string { return v.Version }

// RegisterAgentInstanceRegisterAgentInstance includes the requested fields of the GraphQL type AgentInstance.
type RegisterAgentInstanceRegisterAgentInstance struct {
	InstanceID string `json:"instanceID"`
}

// GetInstanceID returns RegisterAgentInstanceRegisterAgentInstance.InstanceID, and is useful for accessing the field via an interface.
func (v *RegisterAgentInstanceRegisterAgentInstance) GetInstanceID() string { return v.InstanceID }

// RegisterAgentInstanceResponse is returned by RegisterAgentInstance on success.
type RegisterAgentInstanceResponse struct {
	RegisterAgentInstance *RegisterAgentInstanceRegisterAgentInstance `json:"registerAgentInstance"`
}

// GetRegisterAgentInstance returns RegisterAgentInstanceResponse.RegisterAgentInstance, and is useful for accessing the field via an interface.
func (v *RegisterAgentInstanceResponse) GetRegisterAgentInstance() *RegisterAgentInstanceRegisterAgentInstance {
	return v.RegisterAgentInstance
}

// __AckAgentMessagesInput is used internally by genqlient
type __AckAgentMessagesInput struct {
	Input *AckAgentMessagesInput `json:"input,omitempty"`
}

// GetInput returns __AckAgentMessagesInput.Input, and is useful for accessing the field via an interface.
func (v *__AckAgentMessagesInput) GetInput() *AckAgentMessagesInput { return v.Input }

// __HeartbeatAgentInstanceInput is used internally by genqlient
type __HeartbeatAgentInstanceInput struct {
	Input *HeartbeatAgentInstanceInput `json:"input,omitempty"`
}

// GetInput returns __HeartbeatAgentInstanceInput.Input, and is useful for accessing the field via an interface.
func (v *__HeartbeatAgentInstanceInput) GetInput() *HeartbeatAgentInstanceInput { return v.Input }

// __PullAgentMessagesInput is used internally by genqlient
type __PullAgentMessagesInput struct {
	Input *PullAgentMessagesInput `json:"input,omitempty"`
}

// GetInput returns __PullAgentMessagesInput.Input, and is useful for accessing the field via an interface.
func (v *__PullAgentMessagesInput) GetInput() *PullAgentMessagesInput { return v.Input }

// __PushAgentMessageInput is used internally by genqlient
type __PushAgentMessageInput struct {
	Input *PushAgentMessageInput `json:"input,omitempty"`
}

// GetInput returns __PushAgentMessageInput.Input, and is useful for accessing the field via an interface.
func (v *__PushAgentMessageInput) GetInput() *PushAgentMessageInput { return v.Input }

// __RegisterAgentInstanceInput is used internally by genqlient
type __RegisterAgentInstanceInput struct {
	Input *RegisterAgentInstanceInput `json:"input,omitempty"`
}

// GetInput returns __RegisterAgentInstanceInput.Input, and is useful for accessing the field via an interface.
func (v *__RegisterAgentInstanceInput) GetInput() *RegisterAgentInstanceInput { return v.Input }

// The mutation executed by AckAgentMessages.
const AckAgentMessages_Operation = `
mutation AckAgentMessages ($input: AckAgentMessagesInput!) {
	ackAgentMessages(input: $input)
}
`

func AckAgentMessages(
	ctx_ context.Context,
	client_ graphql.Client,
	input *AckAgentMessagesInput,
) (data_ *AckAgentMessagesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AckAgentMessages",
		Query:  AckAgentMessages_Operation,
		Variables: &__AckAgentMessagesInput{
			Input: input,
		},
	}

	data_ = &AckAgentMessagesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AgentBootstrap.
const AgentBootstrap_Operation = `
query AgentBootstrap {
	agentBootstrap {
		agentID
		agentName
		model
		systemPrompt
		tools {
			name
			description
			parameters
			config
		}
		skills {
			name
			content
			entrypoint
			args
		}
		builtinTools {
			name
			enabled
			order
			config
		}
	}
}
`

func AgentBootstrap(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *AgentBootstrapResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AgentBootstrap",
		Query:  AgentBootstrap_Operation,
	}

	data_ = &AgentBootstrapResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by HeartbeatAgentInstance.
const HeartbeatAgentInstance_Operation = `
mutation HeartbeatAgentInstance ($input: HeartbeatAgentInstanceInput!) {
	heartbeatAgentInstance(input: $input)
}
`

func HeartbeatAgentInstance(
	ctx_ context.Context,
	client_ graphql.Client,
	input *HeartbeatAgentInstanceInput,
) (data_ *HeartbeatAgentInstanceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "HeartbeatAgentInstance",
		Query:  HeartbeatAgentInstance_Operation,
		Variables: &__HeartbeatAgentInstanceInput{
			Input: input,
		},
	}

	data_ = &HeartbeatAgentInstanceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by PullAgentMessages.
const PullAgentMessages_Operation = `
query PullAgentMessages ($input: PullAgentMessagesInput!) {
	pullAgentMessages(input: $input) {
		id
		threadID
		text
		sequence
	}
}
`

func PullAgentMessages(
	ctx_ context.Context,
	client_ graphql.Client,
	input *PullAgentMessagesInput,
) (data_ *PullAgentMessagesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "PullAgentMessages",
		Query:  PullAgentMessages_Operation,
		Variables: &__PullAgentMessagesInput{
			Input: input,
		},
	}

	data_ = &PullAgentMessagesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by PushAgentMessage.
const PushAgentMessage_Operation = `
mutation PushAgentMessage ($input: PushAgentMessageInput!) {
	pushAgentMessage(input: $input) {
		id
	}
}
`

func PushAgentMessage(
	ctx_ context.Context,
	client_ graphql.Client,
	input *PushAgentMessageInput,
) (data_ *PushAgentMessageResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "PushAgentMessage",
		Query:  PushAgentMessage_Operation,
		Variables: &__PushAgentMessageInput{
			Input: input,
		},
	}

	data_ = &PushAgentMessageResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by RegisterAgentInstance.
const RegisterAgentInstance_Operation = `
mutation RegisterAgentInstance ($input: RegisterAgentInstanceInput!) {
	registerAgentInstance(input: $input) {
		instanceID
	}
}
`

func RegisterAgentInstance(
	ctx_ context.Context,
	client_ graphql.Client,
	input *RegisterAgentInstanceInput,
) (data_ *RegisterAgentInstanceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "RegisterAgentInstance",
		Query:  RegisterAgentInstance_Operation,
		Variables: &__RegisterAgentInstanceInput{
			Input: input,
		},
	}

	data_ = &RegisterAgentInstanceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
